---
title: Контролирайте последователността на светлините на трафика с Scratch 2
hero_image: images/banner.png
description: Научете как да управлявате светодиодите със светофар и да кодирате последователността на светофара, като използвате Scratch 2
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, scratch
site_areas: jam
hardware: electronic-components
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
- title: Въведение
- title: Какво ще ви трябва
- title: Свържете светодиодите
- title: Контролирайте светодиодите
- title: Последователност на светофарите
