---
title: A közlekedési lámpák szekvenciájának vezérlése karcolás nélkül 2
hero_image: images / banner.png
description: Tanuld meg, hogy irányítsd a jelzőlámpákat és kódolj egy közlekedési lámpa sorozatot a Scratch 2 segítségével
theme: piros
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, scratch
site_areas: jam
hardware: electronic-components
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
-
title: Bevezetés
-
title: Amire szükséged lesz
-
title: Csatlakoztassa a LED-eket
-
title: Irányítsa a LED-eket
-
title: A közlekedési lámpa sorrendje