---
title: A közlekedési lámpák szekvenciájának vezérlése karcolás nélkül 2
hero_image: images / banner.png
description: Tanuld meg, hogy irányítsd a jelzőlámpákat és kódolj egy közlekedési lámpa sorozatot a Scratch 2 segítségével
theme: piros
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programozás-0, fizikai-comp-0
interests: "fizikai számítástechnika"
technologies: "elektronika, fizikai számítástechnika, karcolás"
site_areas: ""
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: Csatlakoztassa a LED-eket
  - 
    title: Irányítsa a LED-eket
  - 
    title: A közlekedési lámpa sorrendje
