---
title: Controlla un semaforo con Scratch 2
hero_image: images/banner.png
description: Impara a controllare un semaforo a LED e a programmare una sequenza di luci con Scratch 2
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, scratch
site_areas: jam
hardware: electronic-components
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
-
title: Introduzione
-
title: Di cosa avrai bisogno
-
title: Collegare i LED
-
title: Controllare i LED
-
title: Il semaforo